" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Bundle "gmarik/Vundle.vim"
Bundle "bling/vim-airline"
Bundle "tpope/vim-sleuth"
Bundle "chriskempson/base16-vim"
Bundle "airblade/vim-gitgutter"
Bundle "Valloric/YouCompleteMe"
Bundle "majutsushi/tagbar"

call vundle#end()
filetype plugin indent on

" Airline
set laststatus=2
let g:airline_powerline_fonts=1

" Tagbar
nmap <silent> <F8> :TagbarOpenAutoClose<CR>

" Syntax coloring
syntax enable
set background=dark
colorscheme base16-3024
hi Normal ctermbg=NONE
hi WarningMsg ctermbg=0

" Formatting
set encoding=utf-8
set tabstop=8
set shiftwidth=4
set expandtab
set autoindent
nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR> " Trim trailing spaces
map <C-k> :pyf /usr/share/clang/clang-format.py<cr>
nmap <C-k> m'ggvG:pyf /usr/share/clang/clang-format.py<cr>''
imap <C-k> <C-o>:pyf /usr/share/clang/clang-format.py<cr>

" Line numbering
if !exists("vimpager")
    set number
    set rnu
    autocmd InsertEnter * :set nornu
    autocmd InsertLeave * :set rnu
    function! NumberToggle()
        if(&rnu == 1)
            set nornu
        else
            set rnu
        endif
    endfunc
    nnoremap <silent> <C-n> :call NumberToggle()<CR>
endif

" Buffer switching
nnoremap <C-b> :buffers<CR>:buffer<Space>

" Vimpager
let vimpager_disable_ansiesc = 1

" Search tweaks
set incsearch
set hlsearch

" Paste mode
set pastetoggle=<F2>

" Window switching
tnoremap <A-h> <C-\><C-n><C-w>h
tnoremap <A-j> <C-\><C-n><C-w>j
tnoremap <A-k> <C-\><C-n><C-w>k
tnoremap <A-l> <C-\><C-n><C-w>l
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l

" Completion
set completeopt=menu,menuone,longest,preview
let g:ycm_confirm_extra_conf=0
let g:ycm_autoclose_preview_window_after_completion=1

" Shortcuts
nnoremap <silent> <F4> :w<CR><C-w>s :terminal make run<CR>
vnoremap <silent> // y/<C-r>"<CR>
vnoremap <C-y> "+y

" Cache
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Misc
set mouse=a
set nowrap
set shell=zsh
set scrolloff=5
set ruler
set backspace=2
set noesckeys
set cursorline
set lazyredraw
map ; :

