## Plugins
eval %sh{
    kak-lsp --kakoune -s $kak_session && echo "
        lsp-enable
        lsp-diagnostic-lines-disable global
    "
}

## General options
set global scrolloff 3,3
set global startup_info_version -1
set global ui_options ncurses_assistant=off

## Visuals
colorscheme base16_termcolors
add-highlighter global/ show-matching
add-highlighter global/ line '%val{cursor_line}' CursorLine
add-highlighter global/ dynregex '%reg{/}' 0:SearchMatches
hook global WinCreate .* %{
    # Enable these on WinCreate so we can:
    # - disable them per window later on
    # - precisely define in which order they should be displayed
    add-highlighter window/number-lines number-lines -hlcursor -separator ' '
    try %{ lsp-diagnostic-lines-enable window }
    git show-diff
}
hook global BufWritePost .* %{ git update-diff }

## Misc bindings
map global normal <C-w> %{ : new<ret> }
map global normal <C-y> %{ <A-|> xsel -ib<ret> }

## Pager use
def -hidden pager-mode %{
    map window normal q %{: quit<ret>}
    remove-highlighter window/number-lines
}
hook global WinSetOption filetype=man %{ pager-mode }

hook -group git-highlight global WinSetOption filetype=git %{
    add-highlighter window/git group
    add-highlighter window/git/ regex '^(commit) ([0-9a-f]+)(.*?)$' 1:yellow 2:red
    add-highlighter window/git/ regex '^([a-zA-Z_-]+:) (.*?)$' 1:green 2:magenta
    add-highlighter window/git/ ref diff
}
hook -group git-highlight global WinSetOption filetype=(?!git).* %{ remove-highlighter window/git }
