#!/usr/bin/zsh

setopt nobgnice

xrdb ~/dotfiles/x/Xresources

# Don't ring bells
xset b off

keynav "loadconfig ~/dotfiles/keynavrc" &
unclutter --timeout 2 --jitter 2 &
udiskie &
redshift-gtk &

if [[ "$HOST" == "Akatsuki" ]]; then
    dunst -config ~/dotfiles/dunstrc &
    vblank_mode=0 compton --vsync=drm \
        --config ~/dotfiles/compton.conf &
fi

if [[ "$HOST" == "Hitagi" ]]; then
    dunst -config ~/dotfiles/dunstrc \
        -geometry "300x5-20+20" -font "Ubuntu Mono 11.5" &
    libinput-gestures &
    nm-applet &
    blueman-applet &
    compton --vsync=opengl-mswc --xrender-sync --xrender-sync-fence \
        --config ~/dotfiles/compton.conf &
fi

~/.fehbg &

~/dotfiles/i3/genconfig
exec i3 -c /var/run/user/$UID/i3config

