#!/usr/bin/zsh

xrdb ~/dotfiles/x/Xresources

# Don't ring bells
xset b off

# Mouse settings
da2013ctl -w off -l off -f 1000
razer-profile

xsettingsd &
pulseaudio --start
autocutsel -fork &
dunst &
keynav &
unclutter --timeout 2 --jitter 2 &
chromium &
ytdl_server.py &
killall -9 qbittorrent; qbittorrent &
thunderbird &
telegram-desktop &
$TERMINAL -title "WeeChat" -e weechat &
dropbox &
nm-applet &
udiskie &
redshift-gtk &

~/.fehbg &
compton &
exec i3

