#!/bin/bash

set -e
timeout=15
name='Bitwarden'

rbw unlock
entry=$(rbw list | gfzf -T "$name" -- --prompt="$name> ")
[[ -n $entry ]] || exit

rbw get "$entry" | { timeout "$timeout" wl-copy -fno & }

notify-send -t $((timeout * 1000)) \
	"Password for $entry copied to clipboard" \
	"You have $timeout seconds to paste it somewhere."
