#!/bin/bash

set -e
name='Bitwarden'

rbw unlock
entry=$(rbw list | gfzf -T "$name" -- --prompt="$name> ")
[[ -n $entry ]] || exit

# Neither wtype nor rbw can eliminate the trailing newline,
# so we have to do it ourselves
password=$(rbw get "$entry")
echo -n "$password" | wtype -

# Do this in two steps so that we don't clobber the clipboard
# if there is no TOTP code
code=$(rbw code "$entry")
echo -n "$code" | wl-copy -o
