#!/bin/bash

set -e
timeout=15

rbw unlock
entry=$(rbw list | fzf)
[[ -n $entry ]] || exit

rbw get "$entry" | { timeout "$timeout" wl-copy -fno & }

notify-send -t $((timeout * 1000)) \
	"Password for $entry copied to clipboard" \
	"You have $timeout seconds to paste it somewhere."
