#!/usr/bin/bash

if [ "$HOSTNAME" == "Akatsuki" ]; then
    fontsize=15
    height=26
else
    fontsize=10
    height=20
fi

/usr/bin/dmenu -fn "xos4 terminus -$fontsize" -h $height -b -i -nb '#333333' -nf '#B2B2B2' -sb '#666666' -sf '#B2B2B2' -dim 0 -dc '#333333' $@

