#!/usr/bin/bash

if [ "$HOSTNAME" == "Akatsuki" ]; then
    fontsize=15
    height=26
else
    fontsize=10
    height=20
fi

/usr/bin/dmenu -fn "xos4 terminus -$fontsize" -h $height -b -i -nb '#F4FBF4' -nf '#5E6E5E' -sb '#8CA68C' -sf '#242924' -dim 0 -dc '#F4FBF4' $@

