#!/bin/bash

# This horrible hack hooks stdin and stdout up from the pipeline
# to fzf, bypassing the terminal emulator
exec $TERMINAL -a modalterm -T dunst \
    100<&0 101>&1 \
    -- bash -c 'exec fzf <&100 >&101'
