#!/bin/sh -e

name='run'
command=$(
    IFS=:
    find $PATH -mindepth 1 -maxdepth 1 \
        2>/dev/null \
        -type f,l -executable \
        -printf "%f\0" \
        | sort -zu \
        | gfzf -T "$name" -- --read0 --prompt="$name> "
)
swaymsg "exec '${command}'"
