#!/usr/bin/env python3

import json
import locale
import math
import multiprocessing as mp
from pathlib import Path
import shlex
import shutil
import subprocess as sp
import sys

music_path = Path("~/music").expanduser()
ogg_path = Path("~/ogg").expanduser()

max_sample_rate = 48000

locale_encoding = locale.nl_langinfo(locale.CODESET)

ffprobe_cmd = shlex.split("ffprobe -print_format json -show_streams")
def transocde(infile):
    outfile = Path(infile).with_suffix(".ogg")
    outfile = ogg_path / outfile.relative_to(music_path)
    if outfile.is_file():
        return
    print(str(outfile.relative_to(ogg_path)))
    outfile = str(outfile)

    probe = (sp.check_output(ffprobe_cmd + [infile], stderr=sp.DEVNULL)
            .decode(locale_encoding))
    probe = json.loads(probe)

    encode_args = []
    for stream in probe["streams"]:
        if stream["codec_type"] == "audio":
            index = stream["index"]

            sample_rate = int(stream["sample_rate"])
            if sample_rate > max_sample_rate:
                target_sample_rate = int(sample_rate / math.ceil(sample_rate / max_sample_rate))
                encode_args += shlex.split("-ar:0:{} {}".format(index, target_sample_rate))

    encode_cmd = (shlex.split("ffmpeg -y -i")
            + [infile]
            + shlex.split("-map 0:a -c:a libopus -b:a 262144 -vbr on")
            + encode_args
            + [outfile])

    sp.call(encode_cmd, stderr=sp.DEVNULL, stdin=sp.DEVNULL)

def inpath(path):
    return str(music_path / path)

def main():
    indirs = list(map(inpath, sys.argv[1:]))

    if len(indirs) == 0:
        print("No input")
        return

    enum_cmd = (["find"]
            + indirs
            + shlex.split("( -name *.flac -or -name *.ogg ) ! -iname *instr*"))
    infiles = sp.check_output(enum_cmd).decode(locale_encoding).splitlines()

    for infile in infiles:
        infile = Path(infile)
        outfile = ogg_path / infile.relative_to(music_path)

        # Create directory structure and copy the cover if they're not already there
        outdir = outfile.parent
        if not outdir.is_dir():
            outdir.mkdir(parents=True, exist_ok=True)
            indir = infile.parent
            for coverfile in ["cover.png", "cover.jpg", "cover.jpeg"]:
                coverpath = indir / coverfile
                if coverpath.is_file():
                    target = outdir / coverfile
                    shutil.copy(str(coverpath), str(target))

    with mp.Pool() as p:
        p.map(transocde, infiles)

main()
