#!/bin/bash

export music="$HOME/music"
export ogg="$HOME/ogg"
threads=$(nproc)

to_vorbis()
{
    subpath=$(dirname "$(relpath "$1" "$music")")
    out=$ogg/$subpath/$(basename "$1" | sed "s/\(.*\)\..*/\1.ogg/")

    # Don't bother if the file is there
    [[ -f "$out" ]] && exit

    echo $out
    ffmpeg -i "$1" -c:a libvorbis -q 8 "$out" &> /dev/null < /dev/null
}
export -f to_vorbis

relpath()
{
    dir1=$(echo $1 | sed "s/'/\\\\'/g")
    dir2=$(echo ${2:-$PWD} | sed "s/'/\\\\'/g")
    python3 << EOF
import os.path
print(os.path.relpath('''$dir1''', '''$dir2'''))
EOF
}
export -f relpath

IFS=$'\n\b'
for dir in $(find $music/$1 -type d)
do
    subpath=$(relpath "$dir" "$music")
    mkdir -p "$ogg/$subpath"
    cp "$music/$subpath/"cover.{png,jpeg,jpg} "$ogg/$subpath" 2> /dev/null
done

find "$music/$1" \( -name "*.flac" -or -name "*.ogg" \) ! -iname "*instr*" -print0 \
    | xargs -0 -P $threads -L1 -ifile bash -c 'to_vorbis "file"'
