#!/bin/bash

profile=$(razercfg -P | grep -o "[0-9]\\+")

if [ $profile -gt 1 -a $1 == "-" ]; then
    let profile--
    razercfg -p $profile
fi

if [ $profile -lt 5 -a $1 == "+" ]; then
    let profile++
    razercfg -p $profile
fi

