#!/bin/bash

dpi=(1200 800 600 300)
ndpi=3

profile=$(cat ~/.razer-profile)

if [ $profile -gt 0 -a $1 == "-" ]; then
    let profile--
fi

if [ $profile -lt $ndpi -a $1 == "+" ]; then
    let profile++
fi

echo $profile > ~/.razer-profile

da2013ctl -w off -l off -f 1000 -r ${dpi[$profile]}
