#!/bin/bash

dpi=(2100 1400 1000 500)
# Yes, I know it's the actual number minus one, don't question sloppy programming
ndpi=3

profile=$(cat ~/.razer-profile)

if [ $profile -gt 0 -a $1 == "-" ]; then
    let profile--
fi

if [ $profile -lt $ndpi -a $1 == "+" ]; then
    let profile++
fi

echo $profile > ~/.razer-profile

da2013ctl -w off -l off -f 1000 -r ${dpi[$profile]}
