#!/bin/bash

gdb --args /usr/bin/telegram-desktop "$@" << EOF
tbreak main
commands
    # Make all circled images into rounded rectangles
    # Original code doesn't matter much
    # This sets some arguments specific to pixRounded and jumps to it
    # The first few arguments are in the same order so no need to touch them
    # mov $0xFFFF,%r9d
    set {short}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+0) = 0xB941
    set {int}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+2) = 0xFFFF
    # mov $0x01,%r8d
    set {short}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+6) = 0xB841
    set {int}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+8) = 0x01
    # jmpq <_ZNK5Image10pixRoundedEN4Data10FileOriginEii16ImageRoundRadiusN4base5flagsI8RectPartEE>
    set {char}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+12) = 0xE9
    set {int}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+13) = (_ZNK5Image10pixRoundedEN4Data10FileOriginEii16ImageRoundRadiusN4base5flagsI8RectPartEE) - (_ZNK5Image10pixCircledEN4Data10FileOriginEii + 17)

    # Make pins not notify by default
    # -mov $0x01,%ecx (imm part only)
    # +mov $0x00,%ecx (imm part only)
    # ...
    # addr32 callq <_ZN2Ui8CheckboxC2EP7QWidgetRK7QStringbRKN5style8CheckboxERKNS6_5CheckE>
    set {int}(_ZN13PinMessageBox7prepareEv+488) = 0x00

    # Delete messages for everyone by default
    # -xor %ecx,%ecx
    # +inc %ecx
    # ...
    # addr32 callq <_ZN2Ui8CheckboxC2EP7QWidgetRK7QStringbRKN5style8CheckboxERKNS6_5CheckE>
    set {short}(_ZN17DeleteMessagesBox7prepareEv+3064) = 0xC1FF

    # Don't pulse mentions
    # -addr32 callq <_ZN13HistoryWidget23enqueueMessageHighlightEN3gsl8not_nullIPN11HistoryView7ElementEEE>
    # +nop
    # +nop
    # +nop
    # +nop
    # +nop
    # +nop
    set {char [6]}(_ZN12HistoryInner10paintEventEP11QPaintEvent+3371) = { 0x90, 0x90, 0x90, 0x90, 0x90, 0x90 }
    set {char [6]}(_ZN12HistoryInner10paintEventEP11QPaintEvent+3657) = { 0x90, 0x90, 0x90, 0x90, 0x90, 0x90 }

    # Disable emoji button hover (JuanPotato)
    # -jmpq   0xD84300 <_ZN11ChatHelpers11TabbedPanel12showAnimatedEv>
    # +retq
    set {char}(_ZN11ChatHelpers11TabbedPanel10otherEnterEv+0) = 0xC3

    # Toggle emoji popup with button click (JuanPotato)
    # -jne <_ZN13HistoryWidget24toggleTabbedSelectorModeEv+168>
    # +nop
    # +nop
    set {short}(_ZN13HistoryWidget24toggleTabbedSelectorModeEv+77) = 0x9090

    # Always default to sending photo or album when possible (udf)
    # addr32 callq <_Z4Authv>
    # -mov 0x6C(%rax),%eax
    # +xor %eax,%eax
    # +nop
    # cmp $0x2,%eax
    set {short}(_ZN12SendFilesBox11initSendWayEv+62) = 0xC031
    set {char}(_ZN12SendFilesBox11initSendWayEv+64) = 0x90
end
run
detach
quit
EOF
