#!/bin/bash

gdb --args /usr/bin/telegram-desktop "$@" << EOF
tbreak _ZN3App9initMediaEv
commands
    # TODO find a way to change this value (it's in RO data)
    #set {int}(_ZN2st20historyMessageRadiusE) = 3

    # Make all circled images into rounded rectangles
    set {char}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+0) = 0x41
    set {char}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+1) = 0xB9
    set {int}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+2) = 0xFFFF
    set {char}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+6) = 0x41
    set {char}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+7) = 0xB8
    set {int}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+8) = 0x01
    set {char}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+12) = 0xE9
    set {int}(_ZNK5Image10pixCircledEN4Data10FileOriginEii+13) = (_ZNK5Image10pixRoundedEN4Data10FileOriginEii16ImageRoundRadiusN4base5flagsI8RectPartEE) - (_ZNK5Image10pixCircledEN4Data10FileOriginEii + 17)

    # Make pins not notify by default
    set {int}(_ZN13PinMessageBox7prepareEv+488) = 0x0

    # Delete messages for everyone by default
    set {short}(_ZN17DeleteMessagesBox7prepareEv+3064) = 0xC1FF
end
run
detach
quit
EOF
