#!/bin/bash
#
# wankparty - Upload files/scrots/urls to wank.party (bye sr.ht)
# By onodera, modified by SirCmpwn and Streetwalrus

set -e

## CONFIGURATION
source ~/.config/wankparty

## FUNCTIONS

# This function sets $file to a selection scrot
selection() {
    uploadme="/tmp/scrot.png"

    # #5081B2
    color="0.3137254901960784, 0.5058823529411764, 0.6980392156862745"
    sel=$(slop -k -b 4 -c "$color" -n -f "-i %i -g %g")
    shotgun $sel "$uploadme"

    word=selection
}

# This function sets $file to an active window scrot
active() {
    uploadme="/tmp/scrot.png"

    shotgun -i $(xdotool getactivewindow) "$uploadme"

    word=active
}

# This function sets $file to your clipboard contents
clipboard() {
    uploadme="/tmp/scrot.txt"

    xclip -o > "$uploadme"

    word=clipboard
}

# This function sets $file an url
url() {
    type="$(echo "$location" | rev | cut -d "." -f 1 | rev)"
    uploadme="/tmp/url.$type"

    wget --quiet "$location" -O "$uploadme"

    word=url
}

# This function sets $file a file
file() {
    if [[ -f "$location" ]]; then
        uploadme="$location"
    else
        echo "File not found."
        exit 1
    fi

    word=file
}

# This function sets $file to a full screen scrot
desktop() {
    uploadme="/tmp/scrot.png"

    shotgun "$uploadme"

    word=desktop
}

jpeg() {
    uploadme2="/tmp/scrot.jpg"

    convert -quality 90 "$uploadme" "$uploadme2"

    echo $uploadme2
}

# This function uploads the $file
upload() {
    # Send notification
    if [[ "$notify" == true ]]; then
        notify-send "Uploading" "$uploadme"
    fi

    url="$(curl -F key="$key" -F file="@$uploadme" --http1.1 "https://wank.party/api/upload" | grep -o -i "https://wank.party/*.[a-z0-9._-]*")"
}

# This function logs the url,  copies the url to the clipboard, and/or opens the url in your browser
feedback() {
    # Copy url to clipboard
    if [[ "$clipboard" == true ]]; then
        echo -n "$url" | xclip -selection primary
        echo -n "$url" | xclip -selection clipboard
    fi

    # Log url
    if [[ "$log" == true ]]; then
        echo "$url" >> "$logfile"
    fi

    # Open url in browser
    if [[ "$browser" == true ]]; then
        xdg-open "$url"
    fi

    # Send notification
    if [[ "$notify" == true ]]; then
        notify-send "Upload complete" "$url"
    fi

    echo "$url"
}

## EXECUTE

if [[ "$#" -ge 1 ]]; then
    case "$@" in
        -h|--help)
            echo "usage: wankparty [options] [file/url]"
            echo "options:"
            echo "  -h,   --help            print help and exit"
            echo "  -p,   --paste               upload your clipboard as text"
            echo "  -s,   --selection       upload selection scrot"
            echo "  -w,   --active          upload active window scrot"
            exit 0
            ;;
        -s|--selection)
            selection
            ;;
        -w|--active)
            active
            ;;
        -p|--paste)
            clipboard
            ;;
        http*)
            location="$@"
            url
            ;;
        *)
            location="$@"
            file
            ;;
    esac
else
    desktop
    jpeg
fi


if [[ "$#" -eq 0 ]]; then
    desktop
    uploadme=$(jpeg)
fi

upload
feedback

