export EDITOR="nvim"
export DIFFPROG="nvim -d"
export BROWSER="firefox-nightly"
export LESS="FRi"
export MANPAGER="nvim -c 'set ft=man' -"
export TERMINAL="urxvt"

export MOZ_ENABLE_WAYLAND=1

export QT_QPA_PLATFORM=wayland-egl
export QT_STYLE_OVERRIDE=adwaita
export QT_QPA_PLATFORMTHEME=qgnomeplatform
export QT_AUTO_SCREEN_SCALE_FACTOR=0

export TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1

export NINJA_STATUS="[%u/%r/%f] "

export PATH="$HOME/dotfiles/scripts:$HOME/bin:$PATH"

# Rust
export PATH="$PATH:$HOME/.cargo/bin"

# Vivado
export _JAVA_AWT_WM_NONREPARENTING=1

if [[ "$HOST" == "Akatsuki" ]]; then
    export MPD_HOST="$HOME/.mpd/socket"

    export XILINX_ISE="/opt/Xilinx/14.7/ISE_DS/ISE/bin/lin64"

    # AOSP/CM
    export JAVA_HOME="/usr/lib/jvm/$(archlinux-java get)"
    export USE_CCACHE=1
    export WITH_SU=true
    export LINEAGE_VERSION_APPEND_TIME_OF_DAY=true
fi

if [[ "$HOST" == "Hitagi" ]]; then
    export MESA_LOADER_DRIVER_OVERRIDE=iris
fi

typeset -U path

