export EDITOR="nvim"
export DIFFPROG="nvim -d"
export BROWSER="firefox-nightly"
export LESS="FRi"
export MANPAGER="nvim +Man!"
export TERMINAL="foot"

export MOZ_ENABLE_WAYLAND=1

export QT_STYLE_OVERRIDE=adwaita
export QT_QPA_PLATFORMTHEME=gtk3
export QT_AUTO_SCREEN_SCALE_FACTOR=0

export WINEDLLOVERRIDES=winemenubuilder.exe=d

export NINJA_STATUS="[%u/%r/%f] "

export PATH="$HOME/dotfiles/scripts:$HOME/bin:$PATH"

# Rust
export PATH="$PATH:$HOME/.cargo/bin"

# Vivado
export _JAVA_AWT_WM_NONREPARENTING=1

if [[ "$HOST" == "Akatsuki" ]]; then
    export MPD_HOST="$HOME/.mpd/socket"

    export XILINX_ISE="/opt/Xilinx/14.7/ISE_DS/ISE/bin/lin64"
fi

if [[ "$HOST" == "Hitagi" ]]; then
    export MESA_LOADER_DRIVER_OVERRIDE=iris
fi

: "${SSH_AUTH_SOCK:=${XDG_RUNTIME_DIR}/yubikey-agent/yubikey-agent.sock}"
export SSH_AUTH_SOCK

typeset -U path

